move_wod:
  ros__parameters:
    plugins:
      - plansys2_move_bt_node
    waypoints: ["living_room", "bathroom", "bedroom", "kitchen", "garage"]
    waypoint_coords:
      living_room: [-5.08, -4.93, 0.0]
      bathroom: [3.92, 1.03, 0.0]
      bedroom: [1.92, -4.97, 0.0]
      kitchen: [-2.03, 1.06, 0.0]
      garage: [-0.85, -10.17, 0.0]

move_wd:
  ros__parameters:
    plugins:
      - plansys2_move_bt_node
    waypoints: ["living_room", "bathroom", "bedroom", "kitchen", "garage"]
    waypoint_coords:
      living_room: [-5.08, -4.93, 0.0]
      bathroom: [3.92, 1.03, 0.0]
      bedroom: [1.92, -4.97, 0.0]
      kitchen: [-2.03, 1.06, 0.0]
      garage: [-0.85, -10.17, 0.0]

pick:
  ros__parameters:
    plugins:
      - plansys2_opengripper_bt_node
      - plansys2_closegripper_bt_node
    waypoints: ["living_room", "bathroom", "bedroom", "kitchen", "garage"]
    waypoint_coords:
      living_room: [-5.08, -4.93, 0.0]
      bathroom: [3.92, 1.03, 0.0]
      bedroom: [1.92, -4.97, 0.0]
      kitchen: [-2.03, 1.06, 0.0]
      garage: [-0.85, -10.17, 0.0]

drop:
  ros__parameters:
    plugins:
      - plansys2_opengripper_bt_node
      - plansys2_closegripper_bt_node
    waypoints: ["living_room", "bathroom", "bedroom", "kitchen", "garage"]
    waypoint_coords:
      living_room: [-5.08, -4.93, 0.0]
      bathroom: [3.92, 1.03, 0.0]
      bedroom: [1.92, -4.97, 0.0]
      kitchen: [-2.03, 1.06, 0.0]
      garage: [-0.85, -10.17, 0.0]

open_door_req:
  ros__parameters:
    plugins:
      - plansys2_closegripper_bt_node
      - plansys2_opengripper_bt_node
      - plansys2_move_bt_node
    waypoints: ["living_room", "bathroom", "bedroom", "kitchen", "garage"]
    waypoint_coords:
      living_room: [-5.08, -4.93, 0.0]
      bathroom: [3.92, 1.03, 0.0]
      bedroom: [1.92, -4.97, 0.0]
      kitchen: [-2.03, 1.06, 0.0]
      garage: [-0.85, -10.17, 0.0]

close_door_req_cmd:
  ros__parameters:
    plugins:
      - plansys2_closegripper_bt_node
      - plansys2_opengripper_bt_node
      - plansys2_move_bt_node
    waypoints: ["living_room", "bathroom", "bedroom", "kitchen", "garage"]
    waypoint_coords:
      living_room: [-5.08, -4.93, 0.0]
      bathroom: [3.92, 1.03, 0.0]
      bedroom: [1.92, -4.97, 0.0]
      kitchen: [-2.03, 1.06, 0.0]
      garage: [-0.85, -10.17, 0.0]
