name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - tests

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Install popf deps
        run: sudo apt-get install libfl-dev
      
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.3.3
        with:
          required-ros-distributions: humble
      
      - name: Create custom repos
        run: wget -O /tmp/all.repos https://raw.githubusercontent.com/IntelligentRoboticsLabs/plansys2_tfd_plan_solver/master/plansys2.repos
      
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.2.5
        with:
          package-name: plansys2_gpsr_tayros2
          import-token: ${{ secrets.WORKFLOW_TOKEN }}
          target-ros2-distro: humble
          vcs-repo-file-url: /tmp/all.repos
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
